---
title: "Lista 2 Programação Estatística"
date: "`r Sys.Date()`"
author : "Lyncoln Sousa"
output:
  rmdformats::readthedown:
    highlight: kate
---


```{r setup, echo=FALSE, cache=FALSE}
library(knitr)
library(rmdformats)
```

# 1)

```{r}
a = 12 ; b = 11 ;c = 10 

if(a + b > c && a + c > b && c + b > a){
  if(a == b && b == c) {
    print("O triângulo é equilátero")
  }
  else if(a == b && b != c || a == c && c !=  b|| b == c && b != a){
    print("O triângulo é isósceles")
  }
  else{
  print("O triângulo é escaleno")
  }
} else{
  print("Não é possível formar um triângulo")
}

```

# 2)

## a)
```{r}
mult_3 = c()
for(passo in 1:100){
  mult_3 = c(mult_3, passo * 3)
}
mult_3
```

## b)
```{r}
mult_3 = c()
for(passo in 1:100){
  aux = passo * 3
  if(aux < 100){
    mult_3 = c(mult_3, aux)
  }
}
mult_3
```

## c)
```{r}
impares = c()
for(passo in 1:200){
  resto = passo%%2 
  if(resto == 1){
    impares = c(impares, passo)
  }
}
impares
```


# 3)

## a)
```{r}
mult_3 = c()
passo = 1
while(length(mult_3) < 100){
  mult_3 = c(mult_3, passo * 3)
  passo = passo + 1
}
mult_3
```

## b)
```{r}
mult_3 = c()
passo = 1
while(passo*3 < 100){
  mult_3 = c(mult_3, passo*3)
  passo = passo + 1
}
mult_3
```


## c)
```{r}
impares = c()
passo = 1
while(length(impares) < 100){
  num = passo%%2
  if(num == 1){
    impares = c(impares, passo)
  }
  passo = passo + 1
}
impares
```

# 4)

## a)
```{r}
matriz = matrix(0, nrow = 10, ncol = 10)
for(i in 1:10){
  matriz[1,i] = 1
}
matriz
```

## b)
```{r}
matriz = matrix(0, nrow = 10, ncol = 10)
for(i in 1:10){
  for(j in 1:10){
    matriz[i,j] = i
  }
}
matriz
```

## c)
```{r}
matriz = matrix(0, nrow = 100, ncol = 100)
for(i in 1:100){
  for(j in 1:100){
    matriz[i,j] = j
  }
}
head.matrix(matriz,c(10,10));tail.matrix(matriz,c(10,10))
```

## d)
```{r}
matriz = matrix(0, nrow = 100, ncol = 100)
for(i in 1:100){
  for(j in 1:100){
    if(i%%2 == 0){
      matriz[i,j] = 2
    }else{
      matriz[i,j] = 1
    }
  }
}
head.matrix(matriz,c(10,10));tail.matrix(matriz,c(10,10))
```

# 5)

## a)
```{r}
matriz = matrix(0, nrow = 100, ncol = 100)
for(i in 1:100){
  matriz[i,i] = i
}
head.matrix(matriz,c(10,10));tail.matrix(matriz,c(10,10))
```

## b)
```{r}
matriz = matrix(0, nrow = 100, ncol = 100)
for(i in 1:100){
  matriz[i,i] = 101 - i
}
head.matrix(matriz,c(10,10));tail.matrix(matriz,c(10,10))
```

# 6)

## a)
```{r}
L1 = list()
for(i in 1:10){
  L1[[i]] = i
}
L1
```

## b)
```{r}
L2 = list()
for(i in 1:10){
  aux = c()
  for(j in 1:i){
    aux = c(aux,1)
  }
  L2[[i]] = aux
}
L2
```

## c)
```{r}
L3 = list()
for(i in 1:10){
  aux = c()
  for(j in 1:10){
    aux = c(aux,i*j)
  }
  L3[[i]] = aux
}
L3
```

## d)
```{r}
L4 = list()
for(i in 1:10){
  aux = c()
  for(j in 1:i){
    aux = c(aux,j*2)
  }
  L4[[i]] = aux
}
L4
```

## e)
```{r}
L5 = list()
for(i in 1:10){
  matriz = matrix(0, nrow = i, ncol = i)
  for(j in 1:i){
    matriz[j,j] = 1
  }
  L5[[i]] = matriz
}
L5


```

# 7)

## a)
```{r}
soma = 0
for(elemento in L1){
  soma = soma + elemento
}
soma
```

## b)
```{r}
soma  = c()
for(elemento in L3){
  aux = 0
  for(numero in elemento){
    aux = aux + numero
  }
  soma = c(soma, aux)
}
soma
```

# 8)

## a)
```{r}
soma  = c()
for(elemento in L4){
  aux = 0
  for(numero in elemento){
    aux = aux + numero
  }
  soma = c(soma, aux)
}
soma
```

## b)
```{r}
v  = c()
for(elemento in L4){
  soma_pos = 0
  for(numero in elemento){
    soma_pos = soma_pos + numero
  }
  if(soma_pos%%5 == 0){
    v = c(v, paste(soma_pos,"é múltiplo de 5"))
  }else{
    v = c(v, paste(soma_pos,"não é múltiplo de 5"))
  }
}
v
```


## c)
```{r}
qtd_m5 = 0
for(elemento in soma){
  if(elemento%%5 == 0){
    qtd_m5 = qtd_m5 + 1
  }
}
qtd_m5
```

# 9)

## a)

```{r}
x0 = 2
r = 3
y = c(x0)
for(passo in 2:100){
  y = c(y, y[passo-1] + r)
}
y
```

## b)
```{r}
formula_soma_pa = (y[1] + y[35])*35/2
soma_r = 0 
for(numero in y[1:35]){
  soma_r = soma_r + numero
}
soma_r
soma_r == formula_soma_pa
```

## c)
```{r}
qtd_mult_4 = 0
for(elemento in y){
  if(elemento%%4 == 0){
    qtd_mult_4 = qtd_mult_4 + 1
  }
}
qtd_mult_4
```
## d)
```{r}
qtd_mult_4_5 = 0
for(elemento in y){
  if(elemento%%4 == 0 && elemento%%5 == 0){
    qtd_mult_4_5 = qtd_mult_4_5 + 1
  }
}
qtd_mult_4_5

```

## e)

```{r}
qtd_mult_4_ou_5 = 0
for(elemento in y){
  if(elemento%%4 == 0 || elemento%%5 == 0){
    qtd_mult_4_ou_5 = qtd_mult_4_ou_5 + 1
  }
}
qtd_mult_4_ou_5
```

## f)

```{r}
x = c()
for(elemento in y){
  if(elemento%%2 == 0){
    x = c(x, elemento)
  }
  else{
    x = c(x,0)
  }
}
x
```

# 10)

## a)
```{r}
fib_12 = c(1,1)
while(length(fib_12) < 12){
  qtd_elementos = length(fib_12)
  fib_12 = c(fib_12, fib_12[qtd_elementos] + fib_12[qtd_elementos-1])
}
fib_12
```

## b)

```{r}
fib_300 = c(1,1)
qtd_elementos = length(fib_300)
soma = fib_300[qtd_elementos] + fib_300[qtd_elementos-1]

while(soma < 300){
  fib_300 = c(fib_300, soma)
  qtd_elementos = length(fib_300)
  soma = fib_300[qtd_elementos] + fib_300[qtd_elementos-1]
}
fib_300
```

## c)

```{r}
fib = c(1,1)
soma = 2
qtd = 2

while(soma < 1000000){
  qtd = qtd + 1
  fib = c(fib[2], soma)
  qtd_elementos = length(fib)
  soma = 0
  for(numero in fib){
    soma = soma + numero
  }
}
qtd

```

