---
title: "Lista 10 Programação Estatística"
author: "Lyncoln Sousa"
output:
  rmdformats::readthedown:
    highlight: kate
---


```{r setup, echo=TRUE, cache=FALSE, error = TRUE,warning=F}
```


# 1)

```{r}
RaizBissecao = function(a,b,f,e){
  if(f(a)*f(b) >= 0) stop("Não existe raiz no intervalo a,b")
  
  while(TRUE){
    m = (a+b)/2
    
    if(f(m) == 0 | abs(b-m) < e) return(m)
    
    if(f(a)*f(m) < 0){
      b = m
    }else{
      a = m
    }
  }
}

RaizBissecao(0,3,f=function(x){x-1},0.000001)
```

# 2)

```{r}
RaizBissecaoRec = function(a,b,f,e){
  if(f(a)*f(b) >= 0) stop("Não existe raiz no intervalo a,b")
  
  m = (a+b)/2
  
  if(f(m) == 0 | abs(b-m) < e) return(m)
  if(f(a)*f(m) < 0) return(RaizBissecaoRec(a,m,f,e))
  
  return(RaizBissecaoRec(m, b, f, e))
}

RaizBissecaoRec(0,3,f=function(x){x-1},0.000001)
```

# 3)

```{r}
RaizBissecaoArray = function(a,b,f,e){
  if(f(a)*f(b) >= 0) stop("Não existe raiz no intervalo a,b")
  aproximacoes = c()
  while(TRUE){
    m = (a+b)/2
    
    if(f(m) == 0 | abs(b-m) < e) {
      aproximacoes = c(aproximacoes,m)
      return(aproximacoes)
    }
    if(f(a)*f(m) < 0){
      b = m
      aproximacoes = c(aproximacoes,m)
    }else{
      a = m
      aproximacoes = c(aproximacoes,m)
    }
  }
}

{
  saida = RaizBissecaoArray(0,3,f=function(x){x-1},0.000001)
  plot(0,xlab="x",ylab="f(x)",xlim=c(0,3),ylim=c(-1,2),type="n")
  grid()
  abline(h=0)
  abline(v=0)
  curve(x-1,col="blue",add=T)
  for(i in 1:length(saida)){
    points(saida[i],0,col="red",pch=18,cex.lab=1)
    text(saida[i],-0.2,i,col="red")
  }  
}
```


```{r}
RaizBissecaoArray_rec = function(a,b,f,e){
  if(f(a)*f(b) >= 0) stop("Não existe raiz no intervalo a,b")
  
  m = (a+b)/2
  
  if(f(m) == 0 | abs(b-m) < e) return(m)
  if(f(a)*f(m) < 0) return(c(m,RaizBissecaoArray_rec(a,m,f,e)))
  
  return(c(m,RaizBissecaoArray_rec(m, b, f, e)))
}

{
  saida = RaizBissecaoArray_rec(0,3,f=function(x){x-1},0.000001)
  plot(0,xlab="x",ylab="f(x)",xlim=c(0,3),ylim=c(-1,2),type="n")
  grid()
  abline(h=0)
  abline(v=0)
  curve(x-1,col="blue",add=T)
  for(i in 1:length(saida)){
    points(saida[i],0,col="red",pch=18,cex.lab=1)
    text(saida[i],-0.2,i,col="red")
  }  
}
```

# 4)

```{r}
f = function(x){2-x^5 -x^3 - x}
```

## a)

```{r}
a = -1
f(a) # > 0
b = 1
f(b) # < 0

#Garatimos que f(a)*f(b) < 0 

f(a)*f(b)
```

## b)
```{r}
RaizBissecao(a,b,f,0.00001)
RaizBissecaoRec(a,b,f,0.00001)
```


## c)
```{r}
raiz = RaizBissecao(a,b,f,0.00001)
{
  plot(0,xlab="x",ylab="f(x)",xlim=c(-1,3),ylim=c(-2,2),type="n")
  grid()
  abline(h=0)
  abline(v=0)
  plot(f,add = T,xlim = c(-3,3))
  points(RaizBissecao(a,b,f,0.00001),0,col = "red")
  text(raiz,-0.2,raiz,col="red")
}

#Observe que o ponto se aproxima bastante do 0 de f(x).
#Também podemos observar se o valor está correto aplicando a função no ponto encontrado.

f(raiz)

#O resultado é muito proximo de 0

```

# 5)

```{r}
f = function(x){exp(x) -1/x}
```

## a)

```{r}
{
  plot(0,xlab="x",ylab="f(x)",xlim=c(-10,10),ylim=c(-2,2),type="n")
  grid()
  abline(h=0)
  abline(v=0)
  plot(f,add = T,xlim = c(-10,10))
}

a = 0.5 ; f(a)
b = 2 ; f(b)
```

## b)

```{r}
RaizBissecao(a,b,f,0.00001)
RaizBissecaoRec(a,b,f,0.00001)
```

## c)

```{r}
raiz = RaizBissecao(a,b,f,0.00001)
{
  plot(0,xlab="x",ylab="f(x)",xlim=c(-1,3),ylim=c(-2,2),type="n")
  grid()
  abline(h=0)
  abline(v=0)
  plot(f,add = T,xlim = c(-3,3))
  points(RaizBissecao(a,b,f,0.00001),0,col = "red")
  text(raiz,-0.2,raiz,col="red")
}

#Observe que o ponto se aproxima bastante do 0 de f(x).
#Também podemos observar se o valor está correto aplicando a função no ponto encontrado.

f(raiz)

#O resultado é muito proximo de 0
```

# 6)

## a)
```{r}
f = function(x){x^2 - 3}
#Possui raiz em sqrt(3) e -sqrt(3)
```

## b)

```{r}
#Dependendo do intervalo escolhido, iremos achar uma raiz diferente, positiva ou negativa.

a = 0 ; f(a) 
b = 3 ; f(b)
```

## c)

```{r}
RaizBissecao(a,b,f,0.00001)
RaizBissecaoRec(a,b,f,0.00001)
```
## d)

```{r}
raiz = RaizBissecao(a,b,f,0.00001)
{
  plot(0,xlab="x",ylab="f(x)",xlim=c(0,3),ylim=c(-2,2),type="n")
  grid()
  abline(h=0)
  abline(v=0)
  plot(f,add = T,xlim = c(-3,3))
  points(RaizBissecao(a,b,f,0.00001),0,col = "red")
  text(raiz,-0.2,raiz,col="red")
}

#Observe que o ponto se aproxima bastante do 0 de f(x).
#Também podemos observar se o valor está correto aplicando a função no ponto encontrado.

f(raiz)

#O resultado é muito proximo de 0
```

```{r}
# caso escolhessemos b = -3, observe:
raiz = RaizBissecao(a,-3,f,0.00001)
{
  plot(0,xlab="x",ylab="f(x)",xlim=c(-3,0),ylim=c(-2,2),type="n")
  grid()
  abline(h=0)
  abline(v=0)
  plot(f,add = T,xlim = c(-3,3))
  points(RaizBissecao(a,-3,f,0.00001),0,col = "red")
  text(raiz,-0.2,raiz,col="red")
}

#Achamos o valor de -sqrt(3)
```


# 7)

## b)
```{r}
f = function(x){x^3/6 + x^2 +x -1}
```

## a)
```{r}
#Podemos visualizar graficamente
{
  plot(0,xlab="x",ylab="f(x)",xlim=c(-6,5),ylim=c(-2,2),type="n")
  grid()
  abline(h=0)
  abline(v=0)
  plot(f,add = T,xlim = c(-10,10))
}
#Temos raizes em:
#(-6,-4); (-3,-1); (0,1)
```

## c)

```{r}
a1 = -6 ; b1 = -4; f(a1)*f(b1)
a2 = -3 ; b2 = -1; f(a2)*f(b2)
a3 = 0 ; b3 = 1; f(a3)*f(b3)
```

## d)

```{r}
RaizBissecao(a1,b1,f,0.00001)
RaizBissecao(a2,b2,f,0.00001)
RaizBissecao(a3,b3,f,0.00001)
```

## e)

```{r}
raiz2 = round(RaizBissecao(a2,b2,f,0.00001),3)
raiz1 = round(RaizBissecao(a1,b1,f,0.00001),3)
raiz3 = round(RaizBissecao(a3,b3,f,0.00001),3)
{
  plot(0,xlab="x",ylab="f(x)",xlim=c(-6,5),ylim=c(-2,2),type="n")
  grid()
  abline(h=0)
  abline(v=0)
  plot(f,add = T,xlim = c(-6,5))
  points(RaizBissecao(a1,b1,f,0.00001),0,col = "red")
  text(raiz1,-0.2,raiz1,col="red")
  points(RaizBissecao(a2,b2,f,0.00001),0,col = "red")
  text(raiz2,-0.2,raiz2,col="red")
  points(RaizBissecao(a3,b3,f,0.00001),0,col = "red")
  text(raiz3,-0.2,raiz3,col="red")
}

```

# 8)

```{r}
{
  plot(0,xlab="x",ylab="f(x)",xlim=c(0,4),ylim=c(-2,2),type="n")
  grid()
  abline(h=0)
  abline(v=0)
  plot(sin,add = T,xlim = c(-10,10))
}
a = 2
b = 3.5
raiz = RaizBissecao(a,b,f = sin, 0.0001);raiz
```


# 9)

```{r}
aproxRaiz = function(x0,e = 0.00000000001){
  if(x0 < 0) stop("Não existe raiz de número negativo")
  
  if(x0 == 1 | x0==0) return(x0)
  
  if(x0 > 1) b = x0
  else b = 1
  
  return(RaizBissecao(0,b,function(x){x^2-x0},e))
}

aproxRaiz(2)
aproxRaiz(3)
aproxRaiz(5)
```

# 10)

```{r}

#Função da lista anterior
pol_exp_delta = function(x,delta = 0.001){
  if(!is.numeric(x)) stop("x tem que ser real")
  soma = 1
  i = 1
  while(TRUE){
    incre = x^(i)/factorial(i)
    
    if(abs(incre) < delta){
      return(soma)
    }else{
    soma = soma + incre
    }
    
    i = i + 1
  }
}

exp_raiz = function(x, e = 0.0000001){
  pol_exp_delta(aproxRaiz(x,e),delta = e)
}

# Verificando com a função pronta do R
exp_raiz(3)
exp(sqrt(3))

```

