---
title: "Lista 1 Programação Estatística"
date: "`r Sys.Date()`"
author: "Lyncoln Sousa"
output:
  rmdformats::readthedown:
    highlight: kate
---


```{r setup, echo=FALSE, cache=FALSE}
library(knitr)
library(rmdformats)
```


# 1)
```{r}
x = 0
y = -1
z = 32
```

## a)
```{r}
a_1 = x+y+z; a_1
a_2 = y*z; a_2
a_3 = z/y; a_3
```

## b)
```{r}
b_1 = z^2  ; b_1
# Ou também
b_1 = z**2 ; b_1
b_2 = z^3 ; b_2
b_3 = z^x ; b_3
```
## c)
```{r  error=TRUE}
c_1 = sqrt(a_1) ; c_1
c_2 = sqrt(x) ; c_2
c_3 = sqrt(b_2/a_1); c_3
```

## d)
```{r}
d_1 = a_2 ^ (1/3); d_1 # Não existe raiz de número negativo
d_2 = (-1/a_3) ^ (1/4); d_2
d_3 = z ^ (2/3); d_3
```

## e)
```{r}
e_1 = abs(x); e_1
e_2 = sqrt(abs(a_2)); e_2
e_3 = abs(1/z) ; e_3
```

## f)
```{r}
f_1 = exp(x) ; f_1
f_2 = exp(x+y+z) ; f_2
f_3 = exp(a_3) ; f_3
```

## g)
```{r}
g_1 = log(x) ; g_1
g_2 = log(x+y+z) ; g_2
g_3 = log(y*z) ; g_3 #A Função log não está definida para números não positivos
```

## h)
```{r}
h_1 = sqrt(pi) ; h_1
h_2 = sqrt(exp(-x^2)) ; h_2
h_3 = sqrt(3*log(4/a_3)) ; h_3 #A Função log não está definida para números não positivos
```


### Obs2:
```{r}
exp(1)
```




# 2)
```{r}
ch1 = "a"
ch2 = "b"
ch3 = "c"
```

## a)
```{r}
ch4 = paste(ch1,".",ch2,".",ch3, sep = ""); ch4
```
## b)
```{r}
ch5 = paste(ch1,ch2,ch3, sep = "") ; ch5
```

## c)
```{r}
ch4 == ch5
```

## d)
```{r}
ch4 != ch5
```


# 3)

## a)
```{r}
18%%5
-5%%2
15%%5
8.3%%3
```

## b)
```{r}
a = 2 #Número qualquer
a%%2 #Se o resto da divisão de a por 2 for igual a 1, temos que a é um número ímpar, caso contrário, a é par.

a%%2 == 0
```

## c)
```{r}
a = 0.3 #Número qualquer
a%%1 # Se o resto for 0, temos que a é inteiro, caso contrário, a é real.
a%%1 == 0
```

## d)
```{r}
a = 0.3
abs(a) == a && a%%1 == 0 
#Ou
a >= 0 && a%%1 == 0

```

# 4)
```{r}
a<-seq(1:10); b<-seq(1,20,by=2); d<-seq(20,1,by=-2)
```

## a)
```{r}
x = b - d ; x
```

## b)
```{r}
y = a * 2; y
```

## c)
```{r}
z = a==b ; z
```

## d)
```{r}
w = d > b ; w
```

# 5)

## a)
```{r}
letters
LETTERS
```

## b)

```{r}
class(letters)
class(LETTERS)
```


## c)
```{r}
length(letters)
length(LETTERS)
```

## d)
```{r}
a = c(LETTERS, letters) ; a
length(a)
class(a)
```

## e)
```{r}
b = paste(LETTERS, letters) ; b
class(b)
length(b)
```

# 6)

## a)
```{r}
matrix(c(1:4,101:104), byrow = F, ncol = 2)
```

## b)
```{r}
matrix(c(1:4,101:104), byrow = T, nrow = 2)
```

## c)
```{r}
matrix(1,ncol = 3, nrow = 3)
```

# 7)
```{r}
A<-matrix(c(1,2,3,4,5,6,7,8,9,10,11,12),4,3)
nrow(A)
ncol(A)

dim(A)
```


# 8)
```{r}
minha_lista = list("Lyncoln",22,c(1.75,58),c(TRUE,TRUE,TRUE)); minha_lista
```

## a)
```{r}
minha_lista[[1]]
```

## b)
```{r}
minha_lista[[2]]
```
## c)
```{r}
minha_lista[[3]][1]
```
## d)
```{r}
minha_lista[[3]][2]
```
## e)
```{r}
minha_lista[[4]][3]
```

# 9)
```{r}
lista_2 = list("Daniel",23,c(1,70,56),c(TRUE,TRUE,FALSE)); lista_2
dados_alunos = list(minha_lista,lista_2);dados_alunos
```

## a)
```{r}
dados_alunos[[1]][[1]]
```
## b)
```{r}
dados_alunos[[2]][[1]]
```
## c)
```{r}
dados_alunos[[1]][[2]][1]
```
## d)
```{r}
dados_alunos[[2]][[4]][1]
```

# 10)

```{r}
obj1 <- list(1,2,3); obj2 <- list(c(1,2,3)); obj3 <- c(1,2,3)
# O obj1 é uma lista que contem 3 elementos
obj1
# O obj2 é uma lista que contem 1 elemento
obj2
# O obj3 é um vetor com 3 elementos
obj3
```


# 11)
```{r}
X<-3; Y<-2; Z<-"2"; A<-"X"; B<-X; C<-"A"; D<-paste(A,C); E<-c(A,C); f<-list(A,C)
```

## a)
```{r}
#Y e Z ---> Z é um caracter enquanto Y é um inteiro 
```
## b)
```{r}
#A e B ---> A é um caracter e B é um inteiro
```
## c)
```{r}
#X e B ---> São iguais
```
## d)
```{r}
#A e C ---> Ambos são caracter, mas A guarda "X" enquanto C guarda "A"
```
## e)
```{r}
#D, E e f ---> D é um caracter único contendo, E é um vetor com 2 caracteres e F é uma lista de tamanho 2.
```








